import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';

const origin = process.env.BASKET_URL || 'http://127.0.0.1:5274';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const context = await browser.newContext({ viewport: { width: 1600, height: 1100 }, reducedMotion: 'no-preference' });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await mkdir('artifacts', { recursive: true });
try {
  await page.goto(`${origin}/capital-flow`);
  await page.locator('.capital-scene[data-running="true"]').waitFor();
  await page.evaluate(() => document.fonts.ready);
  const svg = page.locator('.flow-rails.desktop');
  await svg.evaluate(node => node.setCurrentTime(.4));
  const position = () => svg.locator('[data-flow-particle]').first().evaluate(node => ({ x: node.getCTM().e, y: node.getCTM().f, opacity: Number(getComputedStyle(node).opacity) }));
  const first = await position();
  await page.waitForTimeout(450);
  const second = await position();
  assert.ok(second.x > first.x + 30 && second.opacity > .9, 'a visible coin advances on the path');
  await page.screenshot({ path: 'artifacts/flow-in-motion-1600.png' });
  await svg.evaluate(node => node.setCurrentTime(5.85));
  await page.waitForTimeout(50);
  const branches = await svg.locator('[data-flow-particle]').evaluateAll(nodes => nodes.slice(3).map(node => ({ y: node.getCTM().f, opacity: Number(getComputedStyle(node).opacity) })));
  assert.ok(branches.every(coin => coin.opacity > .9), 'coins reach all three branches together');
  assert.ok(branches[0].y < branches[1].y && branches[1].y < branches[2].y, 'the basket divides into three distinct routes');
  await page.screenshot({ path: 'artifacts/flow-branches-1600.png' });
  await page.getByRole('button', { name: 'Pause capital flow animation' }).click();
  const pausedAt = await svg.evaluate(node => node.getCurrentTime());
  await page.waitForTimeout(250);
  assert.equal(await svg.evaluate(node => node.animationsPaused()), true);
  assert.equal(await svg.evaluate(node => node.getCurrentTime()), pausedAt, 'pause freezes the SVG clock');
  await page.getByRole('button', { name: 'Play capital flow animation' }).click();
  await page.waitForTimeout(150);
  assert.equal(await svg.evaluate(node => node.animationsPaused()), false);
  await page.getByRole('button', { name: 'Builder, 30%' }).click();
  await page.getByRole('heading', { name: '30% to the builder' }).waitFor();
  await page.setViewportSize({ width: 1600, height: 600 });
  await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
  await page.locator('.capital-scene[data-running="false"]').waitFor();
  assert.equal(await svg.evaluate(node => node.animationsPaused()), true, 'offscreen flow stops');

  await page.setViewportSize({ width: 1600, height: 1100 });
  await page.goto(`${origin}/`);
  await page.getByRole('button', { name: '5 people', exact: true }).click();
  assert.equal(await page.locator('.basket-feature .distribution-person').count(), 5);
  await page.getByRole('button', { name: '3 people', exact: true }).click();
  assert.equal(await page.locator('.basket-feature .distribution-person').count(), 3);
  await page.screenshot({ path: 'artifacts/home-refined-1600.png' });

  await page.goto(`${origin}/launch`);
  await page.locator('#handle-0').fill('creator');
  await page.getByRole('button', { name: 'Add recipient' }).click();
  await page.locator('#handle-1').fill('builder');
  await page.getByRole('button', { name: 'Split evenly' }).click();
  await page.getByRole('button', { name: 'Pause payout preview' }).click();
  const recipientBefore = await page.locator('.payout-card p').textContent();
  await page.waitForTimeout(3500);
  assert.equal(await page.locator('.payout-card p').textContent(), recipientBefore, 'payout pause preserves recipient');
  await page.getByRole('button', { name: 'Play payout preview' }).click();
  await page.waitForFunction(previous => document.querySelector('.payout-card p')?.textContent !== previous, recipientBefore, { timeout: 5000 });
  await page.waitForTimeout(500);
  await page.screenshot({ path: 'artifacts/launch-refined-1600.png' });

  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${origin}/capital-flow`);
  await page.locator('.capital-scene[data-running="true"]').waitFor();
  await page.locator('.flow-rails.mobile').evaluate(node => node.setCurrentTime(5.85));
  await page.waitForTimeout(50);
  await page.screenshot({ path: 'artifacts/flow-refined-390.png', fullPage: true });
  const nav = await page.locator('.primary-nav > a > span').evaluateAll(nodes => nodes.map(node => ({ size: parseFloat(getComputedStyle(node).fontSize), width: node.scrollWidth, available: node.parentElement.clientWidth })));
  assert.ok(nav.every(label => label.size >= 14 && label.width <= label.available), 'mobile navigation stays readable without overflowing');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.locator('.capital-scene[data-running="false"]').waitFor();
  assert.equal(await page.locator('[data-flow-particle]').count(), 0, 'reduced motion removes travelling coins');
  assert.equal(await page.evaluate(() => [...document.querySelectorAll('body *')].some(node => getComputedStyle(node).animationName !== 'none')), false);
  assert.deepEqual(errors, []);
  await writeFile('artifacts/motion-report.json', JSON.stringify({ first, second, branches, nav, errors }, null, 2));
  console.log('PASS: visible coin travel, three payout branches, pause/resume, offscreen pause, basket choices, rotating payout preview, mobile labels and reduced motion.');
} finally { await browser.close(); }
