import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';

const origin = process.env.BASKET_URL || 'http://127.0.0.1:5274';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const context = await browser.newContext({ viewport: { width: 1600, height: 1100 }, reducedMotion: 'no-preference' });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await mkdir('artifacts', { recursive: true });
const coinPositions = () => page.locator('.capital-scene [data-flow-particle]').evaluateAll(nodes => nodes.map(node => { const box = node.getBoundingClientRect(); return { id: node.dataset.coin, branch: node.dataset.branch ?? null, state: node.className, x: box.left + box.width / 2, y: box.top + box.height / 2 }; }));
const sameCoins = (before, after) => after.map(coin => [coin, before.find(item => item.id === coin.id)]).filter(([, previous]) => previous);
try {
  await page.goto(`${origin}/capital-flow`);
  await page.locator('.capital-scene[data-running="true"]').waitFor();
  await page.evaluate(() => document.fonts.ready);
  await page.locator('.capital-scene [data-flow-particle]').first().waitFor();
  const first = await coinPositions();
  await page.waitForTimeout(300);
  const second = await coinPositions();
  const travelled = sameCoins(first, second);
  assert.ok(travelled.length > 0, 'a coin stays on screen across two samples');
  assert.ok(travelled.some(([now, before]) => now.x > before.x + 30), 'a coin advances along its rail');
  assert.ok(second.length >= 1, `coins are in flight (${second.length})`);
  const tails = await page.locator('.flow-tails path').evaluateAll(nodes => nodes.map(node => ({ d: node.getAttribute('d'), dash: node.getAttribute('stroke-dasharray'), offset: Number(node.getAttribute('stroke-dashoffset')) })));
  assert.ok(tails.length === second.length * 2 && tails.every(tail => tail.d && tail.dash), 'every coin drags two dashes along a copy of its rail');
  await page.screenshot({ path: 'artifacts/flow-in-motion-1600.png' });
  await page.waitForFunction(() => {
    const coins = [...document.querySelectorAll('.capital-scene [data-branch]')];
    const tops = ['0', '1', '2'].map(branch => coins.find(coin => coin.dataset.branch === branch)).map(coin => coin && coin.getBoundingClientRect().top);
    return tops.every(top => top !== undefined) && tops[0] < tops[1] && tops[1] < tops[2];
  }, null, { timeout: 10000 });
  const branches = (await coinPositions()).filter(coin => coin.branch !== null);
  assert.ok(branches.length >= 3 && branches.every(coin => coin.state.includes('state-cash')), 'the basket divides into three dollar coins on distinct routes');
  await page.screenshot({ path: 'artifacts/flow-branches-1600.png' });
  await page.locator('.flow-node.hit').first().waitFor({ timeout: 5000 });
  await page.locator('.flow-chip').first().waitFor({ timeout: 8000 });
  const chip = await page.locator('.flow-chip').first().textContent();
  assert.ok(['+$5.00', '+$3.00', '+$2.00'].includes(chip), `a payout chip lands on a recipient (${chip})`);
  assert.equal(await page.getByRole('button', { name: 'Pause capital flow animation' }).count(), 0, 'the capital flow has no pause control');
  assert.equal(await page.getByText('Illustrative flow').count(), 0, 'the illustrative label is gone');
  await page.getByRole('button', { name: 'Builder, 30%' }).click();
  await page.getByRole('heading', { name: '30% to the builder' }).waitFor();
  await page.setViewportSize({ width: 1600, height: 600 });
  await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
  await page.locator('.capital-scene[data-running="false"]').waitFor();
  const frozenBefore = await coinPositions();
  await page.waitForTimeout(400);
  const frozenAfter = await coinPositions();
  assert.ok(frozenBefore.length > 0, 'coins remain in place while the flow is offscreen');
  assert.deepEqual(frozenAfter, frozenBefore, 'the offscreen flow stops moving');

  await page.setViewportSize({ width: 1600, height: 1100 });
  await page.goto(`${origin}/`);
  await page.getByRole('button', { name: '5 people', exact: true }).click();
  assert.equal(await page.locator('.basket-feature .distribution-person').count(), 5);
  await page.getByRole('button', { name: '3 people', exact: true }).click();
  assert.equal(await page.locator('.basket-feature .distribution-person').count(), 3);
  await page.locator('.hero-art').hover({ position: { x: 60, y: 60 } });
  await page.waitForTimeout(100);
  const tilt = await page.locator('.hero-art').evaluate(node => node.style.getPropertyValue('--tilt-y'));
  assert.ok(tilt && tilt !== '0deg', `hovering the artwork tilts it (${tilt})`);
  await page.mouse.move(10, 10);
  await page.waitForTimeout(100);
  assert.equal(await page.locator('.hero-art').evaluate(node => node.style.getPropertyValue('--tilt-y')), '', 'leaving the artwork resets it');
  await page.screenshot({ path: 'artifacts/home-refined-1600.png' });

  await page.goto(`${origin}/launch`);
  await page.locator('#handle-0').fill('creator');
  await page.getByRole('button', { name: 'Add recipient' }).click();
  await page.locator('#handle-1').fill('builder');
  await page.getByRole('button', { name: 'Split evenly' }).click();
  await page.getByRole('button', { name: 'Pause payout preview' }).click();
  const recipientBefore = await page.locator('.payout-card p').textContent();
  await page.waitForTimeout(3500);
  assert.equal(await page.locator('.payout-card p').textContent(), recipientBefore, 'payout pause preserves recipient');
  await page.getByRole('button', { name: 'Play payout preview' }).click();
  await page.waitForFunction(previous => document.querySelector('.payout-card p')?.textContent !== previous, recipientBefore, { timeout: 5000 });
  await page.waitForTimeout(500);
  await page.screenshot({ path: 'artifacts/launch-refined-1600.png' });

  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${origin}/capital-flow`);
  await page.locator('.capital-scene[data-running="true"]').waitFor();
  await page.locator('.capital-scene [data-branch]').first().waitFor({ timeout: 10000 });
  await page.screenshot({ path: 'artifacts/flow-refined-390.png', fullPage: true });
  const nav = await page.locator('.primary-nav > a > span').evaluateAll(nodes => nodes.map(node => ({ size: parseFloat(getComputedStyle(node).fontSize), width: node.scrollWidth, available: node.parentElement.clientWidth })));
  assert.ok(nav.every(label => label.size >= 14 && label.width <= label.available), 'mobile navigation stays readable without overflowing');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.locator('.capital-scene[data-running="false"]').waitFor();
  assert.equal(await page.locator('[data-flow-particle]').count(), 0, 'reduced motion removes travelling coins');
  await page.waitForFunction(() => document.querySelectorAll('.flow-chip').length === 0, null, { timeout: 3000 });
  assert.equal(await page.evaluate(() => [...document.querySelectorAll('body *')].some(node => getComputedStyle(node).animationName !== 'none')), false);
  assert.deepEqual(errors, []);
  await writeFile('artifacts/motion-report.json', JSON.stringify({ first, second, branches, chip, nav, errors }, null, 2));
  console.log('PASS: coins travel every stage, split into three payouts, pulse nodes and land as chips; no pause control; offscreen freeze; basket choices; artwork tilt; rotating payout preview; mobile labels and reduced motion.');
} finally { await browser.close(); }
